spring:
  application:
    name: next-please
  jpa:
    hibernate:
      ddl-auto: validate

security:
  secretKey: AmhJBaVu/Es35JAc9eSS5RIELpQ6dDv1FyAkNDs3ReM=
  staffExpirationMs: 3600000
  patientExpirationMs: 3600000